AceEditorBundle_homepage:
    pattern:  /
    defaults: { _controller: AceEditorBundle:Default:index }

AceEditorBundle_list:
    pattern:  /list
    defaults: { _controller: AceEditorBundle:Default:list }

AceEditorBundle_editor:
    pattern:  /edit/{project_name}
    defaults: { _controller: AceEditorBundle:Default:edit}

AceEditorBundle_fetchexample:
    pattern:  /fetch/example/{type}/{category}/{name}
    defaults: { _controller: AceEditorBundle:Default:fetchExample}

AceEditorBundle_compile:
    pattern:  /compile
    defaults: { _controller: AceEditorBundle:Default:compile }

# AceEditorBundle_compile:
#     pattern:  /compile/{filename}
#     defaults: { _controller: AceEditorBundle:Default:compile }

AceEditorBundle_download:
    pattern:  /download/{project_name}/{type}
    defaults: { _controller: AceEditorBundle:Default:download, type: file }
    
AceEditorBundle_options:
    pattern:  /options
    defaults: { _controller: AceEditorBundle:Default:options }
    
AceEditorBundle_setoptions:
    pattern:  /setoptions
    defaults: { _controller: AceEditorBundle:Default:setoptions }

AceEditorBundle_checkpass:
    pattern:  /checkpass
    defaults: { _controller: AceEditorBundle:Default:checkpass }

AceEditorBundle_checkmail:
    pattern:  /checkmail
    defaults: { _controller: AceEditorBundle:Default:checkmail }

AceEditorBundle_user:
    pattern:  /user/{user}
    defaults: { _controller: AceEditorBundle:Default:user }
